FROM node:22-alpine

WORKDIR /app

# Copiar package.json y package-lock.json
COPY package*.json ./

# Instalar dependencias
RUN npm install

# Copiar el resto del código
COPY . .

# Exponer puerto
EXPOSE 4200

# Comando para iniciar servidor de desarrollo
CMD ["npm", "start", "--", "--host", "0.0.0.0"]
