<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260204212645 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE alerta (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nombre VARCHAR(255) NOT NULL, codigos_cpv JSON DEFAULT NULL, tipos_contrato JSON DEFAULT NULL, provincias JSON DEFAULT NULL, importe_minimo NUMERIC(18, 2) DEFAULT NULL, importe_maximo NUMERIC(18, 2) DEFAULT NULL, palabras_clave VARCHAR(500) DEFAULT NULL, activa BOOLEAN NOT NULL, notificar_email BOOLEAN NOT NULL, ultima_notificacion TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, total_notificaciones INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, usuario_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4C3B123DB38439E ON alerta (usuario_id)');
        $this->addSql('CREATE TABLE licitacion (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, id_place VARCHAR(100) NOT NULL, expediente VARCHAR(100) NOT NULL, titulo VARCHAR(1000) NOT NULL, estado VARCHAR(20) NOT NULL, estado_descripcion VARCHAR(50) DEFAULT NULL, tipo_contrato VARCHAR(10) NOT NULL, tipo_contrato_descripcion VARCHAR(100) DEFAULT NULL, subtipo VARCHAR(20) DEFAULT NULL, importe_sin_iva NUMERIC(18, 2) DEFAULT NULL, importe_con_iva NUMERIC(18, 2) DEFAULT NULL, codigos_cpv JSON DEFAULT NULL, provincia VARCHAR(100) DEFAULT NULL, codigo_nuts VARCHAR(20) DEFAULT NULL, tipo_procedimiento VARCHAR(20) DEFAULT NULL, tipo_procedimiento_descripcion VARCHAR(200) DEFAULT NULL, fecha_publicacion DATE DEFAULT NULL, fecha_limite_presentacion TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, fecha_adjudicacion DATE DEFAULT NULL, duracion_meses INT DEFAULT NULL, url_licitacion VARCHAR(500) DEFAULT NULL, descripcion TEXT DEFAULT NULL, documentos JSON DEFAULT NULL, criterios_adjudicacion JSON DEFAULT NULL, num_ofertas INT DEFAULT NULL, adjudicatario_nombre VARCHAR(500) DEFAULT NULL, adjudicatario_nif VARCHAR(20) DEFAULT NULL, importe_adjudicacion NUMERIC(18, 2) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, raw_xml TEXT DEFAULT NULL, organo_contratante_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8AC097469A9812FD ON licitacion (id_place)');
        $this->addSql('CREATE INDEX IDX_8AC097465CE812C5 ON licitacion (organo_contratante_id)');
        $this->addSql('CREATE INDEX idx_expediente ON licitacion (expediente)');
        $this->addSql('CREATE INDEX idx_estado ON licitacion (estado)');
        $this->addSql('CREATE INDEX idx_tipo_contrato ON licitacion (tipo_contrato)');
        $this->addSql('CREATE INDEX idx_fecha_publicacion ON licitacion (fecha_publicacion)');
        $this->addSql('CREATE INDEX idx_fecha_limite ON licitacion (fecha_limite_presentacion)');
        $this->addSql('CREATE INDEX idx_importe ON licitacion (importe_sin_iva)');
        $this->addSql('CREATE INDEX idx_provincia ON licitacion (provincia)');
        $this->addSql('CREATE TABLE organo_contratante (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nif VARCHAR(20) NOT NULL, nombre VARCHAR(500) NOT NULL, dir3 VARCHAR(50) DEFAULT NULL, id_plataforma VARCHAR(50) DEFAULT NULL, tipo_administracion VARCHAR(20) DEFAULT NULL, codigo_actividad VARCHAR(100) DEFAULT NULL, direccion VARCHAR(500) DEFAULT NULL, municipio VARCHAR(100) DEFAULT NULL, provincia VARCHAR(100) DEFAULT NULL, codigo_postal VARCHAR(10) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, telefono VARCHAR(50) DEFAULT NULL, url_perfil VARCHAR(500) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8F446884ADE62BBB ON organo_contratante (nif)');
        $this->addSql('CREATE INDEX idx_organo_nif ON organo_contratante (nif)');
        $this->addSql('CREATE TABLE usuario (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, nombre VARCHAR(255) DEFAULT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, activo BOOLEAN NOT NULL, notificaciones_email BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON usuario (email)');
        $this->addSql('ALTER TABLE alerta ADD CONSTRAINT FK_4C3B123DB38439E FOREIGN KEY (usuario_id) REFERENCES usuario (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE licitacion ADD CONSTRAINT FK_8AC097465CE812C5 FOREIGN KEY (organo_contratante_id) REFERENCES organo_contratante (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE alerta DROP CONSTRAINT FK_4C3B123DB38439E');
        $this->addSql('ALTER TABLE licitacion DROP CONSTRAINT FK_8AC097465CE812C5');
        $this->addSql('DROP TABLE alerta');
        $this->addSql('DROP TABLE licitacion');
        $this->addSql('DROP TABLE organo_contratante');
        $this->addSql('DROP TABLE usuario');
    }
}
